/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.events;
import controllers.mainmenu;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.methods;
import static views.DASHBOARD.table_activities;
import static views.DASHBOARD.text_activities;

/**
 *
 * @author SPM
 */
public class EVENTSUBJECT extends javax.swing.JFrame {

    /**
     * Creates new form EVENTS
     */
    public EVENTSUBJECT() {
        initComponents();
        events.searchSubject(subjecttable);
        setLocationRelativeTo(null);
        events.eventSubjectForm();
        subjecttable.getTableHeader().setFont(new java.awt.Font("Century Gothic", 1, 12));
        loadedsubject.getTableHeader().setFont(new java.awt.Font("Century Gothic", 1, 12));
//        jButton2.setEnabled(false);
//        jButton1.setEnabled(true);
//        jButton3.setEnabled(true);
//        jButton4.setEnabled(false);
        button_save1.setEnabled(false);
        button_save.setEnabled(false);
        count1();
        count2();

//        button_active.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjecttable = new controllers.TableStyle(){
            public boolean isCellEditable(int rowIndex, int columnIndex){
                switch (columnIndex){
                    case 0:
                    return false;
                    default:
                    return true;
                }
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        loadedsubject = new controllers.TableStyle(){
            public boolean isCellEditable(int rowIndex, int columnIndex){
                switch (columnIndex){
                    case 0:
                    return false;
                    default:
                    return true;
                }
            }
        };
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        event_current = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        button_save1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 71, 161), 3));

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Event Accepted_50px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Shruti", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Event Subject Load Form");

        jLabel3.setBackground(new java.awt.Color(13, 71, 161));
        jLabel3.setFont(new java.awt.Font("Vrinda", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        jLabel4.setText("Event Name");

        subjecttable.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
        subjecttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Subject ID"
            }
        ));
        subjecttable.setFillsViewportHeight(true);
        subjecttable.setGridColor(new java.awt.Color(255, 255, 255));
        subjecttable.setRowHeight(20);
        subjecttable.setRowMargin(2);
        subjecttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjecttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjecttable);

        loadedsubject.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
        loadedsubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID"
            }
        ));
        loadedsubject.setFillsViewportHeight(true);
        loadedsubject.setGridColor(new java.awt.Color(255, 255, 255));
        loadedsubject.setRowHeight(20);
        loadedsubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadedsubjectMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(loadedsubject);

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        button_save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        event_current.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        event_current.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        event_current.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                event_currentPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel10.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel10.setText("Loaded Subjects");

        button_save1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_save1.setText("Record Attendance");
        button_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_save1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton3.setText(">>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton4.setText("<<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel11.setText("Available Subjects Enrolled");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(event_current, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_save1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(399, 399, 399))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(event_current, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_save1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tab = new DefaultTableModel();
        tab = (DefaultTableModel) loadedsubject.getModel();
        String subject = subjecttable.getValueAt(subjecttable.getSelectedRow(), 0).toString();
        int counter = 0;
        for (int rows = 0; rows < loadedsubject.getRowCount(); rows++) {
            if (subject.equals(loadedsubject.getValueAt(rows, 0))) {
                counter++;
            }
        }
        if (counter > 0) {
            JOptionPane.showMessageDialog(null, "Duplicate Entries detected", "Error Message", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) subjecttable.getModel();////DEFAULT MODEL PARA SA PAG UPDATE SA  ASSESSED TABLE
            int numRows = subjecttable.getSelectedRows().length;
            for (int i = 0; i < numRows; i++) {
                tab.addRow(new Object[]{subjecttable.getValueAt(subjecttable.getSelectedRow(), 0).toString()});
                model.removeRow(subjecttable.getSelectedRow());
            }
//            tab.addRow(new Object[]{subjecttable.getValueAt(subjecttable.getSelectedRow(), 0).toString()});
            count1();
            count2();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tab = new DefaultTableModel();
        tab = (DefaultTableModel) subjecttable.getModel();

        String subject = loadedsubject.getValueAt(loadedsubject.getSelectedRow(), 0).toString();
        int counter = 0;
        for (int rows = 0; rows < subjecttable.getRowCount(); rows++) {
            if (subject.equals(subjecttable.getValueAt(rows, 0))) {
                counter++;
            }
        }
        if (counter > 0) {
            JOptionPane.showMessageDialog(null, "Duplicate Entries detected", "Error Message", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) loadedsubject.getModel();////DEFAULT MODEL PARA SA PAG UPDATE SA  ASSESSED TABLE
            int numRows = loadedsubject.getSelectedRows().length;
            for (int i = 0; i < numRows; i++) {
                tab.addRow(new Object[]{loadedsubject.getValueAt(loadedsubject.getSelectedRow(), 0).toString()});
                model.removeRow(loadedsubject.getSelectedRow());
            }
//            tab.addRow(new Object[]{subjecttable.getValueAt(subjecttable.getSelectedRow(), 0).toString()});
            count1();
            count2();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        if (events.SaveSubjectEvents(loadedsubject) == 1) {
            button_save1.setEnabled(true);
            mainmenu.searchActivities(text_activities, table_activities);//display activities panel
        }

    }//GEN-LAST:event_button_saveActionPerformed

    private void event_currentPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_event_currentPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_event_currentPopupMenuWillBecomeInvisible

    private void button_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_save1ActionPerformed
        new ATTENDANCE(event_current.getSelectedItem().toString()).setVisible(true);
        dispose();
    }//GEN-LAST:event_button_save1ActionPerformed
    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void loadedsubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadedsubjectMouseClicked
        jButton2.setEnabled(true);
        jButton4.setEnabled(true);
        jButton3.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_loadedsubjectMouseClicked

    private void subjecttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjecttableMouseClicked
jButton2.setEnabled(false);
        jButton4.setEnabled(false);
        jButton3.setEnabled(true);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_subjecttableMouseClicked

    void count1() {
        if (subjecttable.getRowCount() > 0) {
            jButton1.setEnabled(true);
            jButton3.setEnabled(true);
            subjecttable.setRowSelectionInterval(0, 0);
        } else {
            jButton1.setEnabled(false);
            jButton3.setEnabled(false);
        }
    }

    void count2() {
        if (loadedsubject.getRowCount() > 0) {
            jButton2.setEnabled(true);
            loadedsubject.setRowSelectionInterval(0, 0);
            jButton4.setEnabled(true);
            button_save.setEnabled(true);
        } else {
              button_save.setEnabled(false);
            jButton2.setEnabled(false);
            jButton4.setEnabled(false);
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel tab = new DefaultTableModel();
        tab = (DefaultTableModel) loadedsubject.getModel();

        for (int rows = 0; rows < subjecttable.getRowCount(); rows++) {

            tab.addRow(new Object[]{subjecttable.getValueAt(rows, 0).toString()});

        }

        DefaultTableModel tab2 = new DefaultTableModel();
        tab2 = (DefaultTableModel) subjecttable.getModel();
        for (int rows = subjecttable.getRowCount() - 1; rows >= 0; rows--) {
            tab2.removeRow(rows);
        }
        count1();
        count2();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel tab = new DefaultTableModel();
        tab = (DefaultTableModel) subjecttable.getModel();

        for (int rows = 0; rows < loadedsubject.getRowCount(); rows++) {

            tab.addRow(new Object[]{loadedsubject.getValueAt(rows, 0).toString()});

        }

        DefaultTableModel tab2 = new DefaultTableModel();
        tab2 = (DefaultTableModel) loadedsubject.getModel();
        for (int rows = loadedsubject.getRowCount() - 1; rows >= 0; rows--) {
            tab2.removeRow(rows);
        }
        count1();
        count2();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EVENTSUBJECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EVENTSUBJECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EVENTSUBJECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EVENTSUBJECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EVENTSUBJECT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_save;
    public static javax.swing.JButton button_save1;
    public static javax.swing.JComboBox event_current;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable loadedsubject;
    private javax.swing.JTable subjecttable;
    // End of variables declaration//GEN-END:variables
}
